FROM ruby:2.5
LABEL maintainer="u6k.apps@gmail.com"

RUN apt-get update && \
    apt-get install -y \
        nodejs && \
    apt-get clean

WORKDIR /var/myapp

COPY . .

RUN bundle install

ENV PATH /usr/local/bundle/bin:$PATH

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
