shared:
  s3_region: <%= ENV["S3_REGION"] %>
  s3_access_key: <%= ENV["S3_ACCESS_KEY"] %>
  s3_secret_key: <%= ENV["S3_SECRET_KEY"] %>
  s3_endpoint: <%= ENV["S3_ENDPOINT"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
